apiVersion: v2
name: icinga2
icon: https://icinga.com/docs/icinga-2/latest/assets/images/favicon.png
description: Icinga is a monitoring system which checks the availability of your network resources, notifies users of outages, and generates performance data for reporting.
type: application
version: 0.1.1
appVersion: "2.13.5"
