nameOverride: ""
fullnameOverride: ""

nodeName:
parent:
master: true
endpoints: []
#  - name: test
#    host: fqdn
zones: []
#  - name: master
#    endpoints: []
#  - name: global-templates
#    global: true
#  - name: director-global
#    global: true
features: {}
#  <name>:
#    type: <objecttype>
#    <options...>
#  checker:
#    type: CheckerComponent
icinga_ca:
  host:
  port: 5665
  pki:

api:
  accept_config: false
  accept_commands: false
  users: []
#    - name: foo
#      password: loremipsum
#      permissions: ["*"]

icinga2:
  image:
    repository: ghcr.io/g0dscookie/icinga2
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  imagePullSecrets: []

  persistence:
    enabled: false
    size: 1Gi
    storageClass: ""
    accessMode: ReadWriteOnce
    annotations: {}
    #  "helm.sh/resource-policy": keep

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}

  service:
    type: ClusterIP
    port: 5665
    externalIPs: []

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}
