apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "icinga2.fullname" . }}
  labels:
    {{- include "icinga2.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "icinga2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.icinga2.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "icinga2.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.icinga2.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "icinga2.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.icinga2.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.icinga2.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.icinga2.image.pullPolicy }}
          ports:
            - name: api
              containerPort: 5665
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: api
          readinessProbe:
            httpGet:
              path: /
              port: api
          resources:
            {{- toYaml .Values.icinga2.resources | nindent 12 }}
      {{- with .Values.icinga2.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.icinga2.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.icinga2.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "icinga2.fullname" . }}-data
  {{- with .Values.icinga2.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.icinga2.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.icinga2.persistence.size }}
  {{- if .Values.icinga2.persistence.storageClass }}
  storageClassName: {{ .Values.icinga2.persistence.storageClass }}
  {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "icinga2.fullname" . }}-init-config
data:
  icinga2.json: |
    {
      "node": {
        "name": {{ .Values.nodeName | quote }},
        {{- if .Values.parent -}}
        "zone": true,
        "parent": {{ .Values.parent | quote }}
        {{- else -}}
        "zone": false
        {{- end -}}
      },
      "endpoints": [
        {{- range .Values.endpoints -}}
        {
          
        }
        {{- end -}}
      ]
    }
