{{- if not .Values.icinga2.service.hostNetwork -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "icinga2.fullname" . }}
  labels:
    {{- include "icinga2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.icinga2.service.type }}
  ports:
    - port: {{ .Values.icinga2.service.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "icinga2.selectorLabels" . | nindent 4 }}
  {{- if .Values.icinga2.service.externalIPs }}
  externalIPs:
    {{- .Values.icinga2.service.externalIPs | toYaml | nindent 4 }}
  {{- end }}
{{- end -}}
