apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "icinga2.fullname" . }}
  labels:
    {{- include "icinga2.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "icinga2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.icinga2.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "icinga2.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.icinga2.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.icinga2.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.icinga2.securityContext | nindent 12 }}
          image: "{{ .Values.icinga2.image.repository }}:{{ .Values.icinga2.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.icinga2.image.pullPolicy }}
          {{- if or .Values.icinga_ca.host .Values.icinga_ca.pki }}
          env:
            - name: ICINGA_CA_NODE
              value: {{ .Values.icinga_ca.host }}
            - name: ICINGA_CA_PORT
              value: {{ .Values.icinga_ca.port | quote }}
            {{- if .Values.icinga_ca.pki }}
            - name: ICINGA_PKI
              valueFrom:
                secretKeyRef:
                  name: {{ include "icinga2.fullname" . }}-secrets
                  key: pki
            {{- end }}
          {{- end }}
          ports:
            - name: api
              containerPort: 5665
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /
              port: api
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /
              port: api
          resources:
            {{- toYaml .Values.icinga2.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
            {{- if .Values.icinga2.persistence.enabled }}
            - name: data
              mountPath: /var/lib/icinga2
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "icinga2.fullname" . }}-config
        {{- if .Values.icinga2.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "icinga2.fullname" . }}-data
        {{- end }}
      {{- with .Values.icinga2.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.icinga2.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.icinga2.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
