apiVersion: v1
kind: Service
metadata:
  name: {{ include "aptly.fullname" . }}
  labels:
    {{- include "aptly.labels" . | nindent 4 }}
spec:
  type: {{ .Values.aptly.service.type }}
  ports:
    - port: {{ .Values.aptly.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aptly.selectorLabels" . | nindent 4 }}
    helm.sh/app: aptly
