{{- if .Values.nginx.ingress.enabled -}}

{{- $fullname := include "aptly.fullname" . -}}
{{- $labels := include "aptly.labels" . -}}
{{- $svc := .Values.nginx.service -}}
{{- $ingress := .Values.nginx.ingress -}}

{{- range $idx, $val := .Values.nginx.ingress.paths }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $fullname }}-public-{{ $idx }}"
  labels:
    {{- $labels | nindent 4 }}
  {{- $annotations := merge ($val.annotations | default dict) $ingress.annotations -}}
  {{- with $annotations }}
  annotations:
    {{- . | toYaml |  nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $ingress.className }}
  {{- if $ingress.tls }}
  tls:
    {{- range $ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ $ingress.hostname }}
      http:
        paths:
          - path: {{ $val.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullname }}-public
                port:
                  number: {{ $svc.port }}
{{- end }}
{{- end }}
