apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "aptly.fullname" . }}"
  labels:
    {{- include "aptly.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
