# This is the definition of the required ssl certificate for the mail system
# It will be issued by cert-manager
{{- if and .Values.ingress.enabled .Values.certmanager.enabled }}
apiVersion: {{ .Values.certmanager.apiVersion }}
kind: Certificate
metadata:
  name: {{ include "archisteamfarm.fullname" . }}-certificate
spec:
  secretName: {{ include "archisteamfarm.fullname" . }}-certificate
  # re-new certificate when it expires in less than 60 days
  renewBefore: 1440h0m0s
  commonName: {{ .Values.hostname }}
  dnsNames: [{{ .Values.hostname }}]
  issuerRef:
    kind: {{ .Values.certmanager.issuerType }}
    name: {{ .Values.certmanager.issuerName }}
{{- end }}