apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "archisteamfarm.fullname" . }}-init-config
data:
  ASF.json: |
    {
      "IPCPassword": {{ .Values.initialPassword | quote }},
      "SteamOwnerID": {{ .Values.steamId }},
      "Headless": true
    }
  IPC.config: |
    {
      "Kestrel": {
        "Endpoints": {
          "HTTP": {
            "Url": "http://*:1242"
          }
        }
      }
    }