{{- if .Values.ingress.enabled -}}

{{- $fullName := include "archisteamfarm.fullname" . -}}
{{- $hostname := .Values.hostname -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "archisteamfarm.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.certmanager.enabled }}
  tls:
    - hosts: [{{ $hostname }}]
      secretName: {{ $fullName }}-certificate
  {{- end }}
  rules:
    - host: {{ $hostname }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 1242
{{- end }}