apiVersion: v1
kind: Service
metadata:
  name: {{ include "passbolt.fullname" . }}
  labels:
    {{- include "passbolt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.passbolt.service.type }}
  ports:
    - port: {{ .Values.passbolt.service.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.passbolt.service.https }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "passbolt.selectorLabels" . | nindent 4 }}
    helm.sh/app: passbolt
