apiVersion: v1
kind: Secret
metadata:
  name: {{ include "passbolt.fullname" . }}-secrets
  labels:
    {{- include "passbolt.labels" . | nindent 4 }}
type: Opaque
data:
  {{- (include "passbolt.secrets" .) | nindent 2 -}}