{{- if .Values.passbolt.persistence.gpg.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "passbolt.fullname" . }}-gpg"
  labels:
    {{- include "passbolt.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.passbolt.persistence.gpg.accessMode }}
  resources:
    requests:
      storage: {{ .Values.passbolt.persistence.gpg.size }}
  storageClassName: {{ .Values.passbolt.persistence.gpg.storageClassName | quote }}
{{- end }}

{{- if and .Values.passbolt.persistence.jwt.enabled .Values.passbolt.jwt.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "passbolt.fullname" . }}-jwt"
  labels:
    {{- include "passbolt.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.passbolt.persistence.jwt.accessMode }}
  resources:
    requests:
      storage: {{ .Values.passbolt.persistence.jwt.size }}
  storageClassName: {{ .Values.passbolt.persistence.jwt.storageClassName | quote }}
{{- end }}